FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install python3 -y
RUN apt-get install python3-pip -y
RUN apt-get install vim -y

RUN pip3 install --no-cache-dir requests

COPY script.py .

CMD ["python3", "script.py"]
